# Ambiguous (2 cols)
performance:
  size: [15, 5]
  dpi: 150
  line_width: 3
  fontsize:
    title: 20
    sub_title: 18
    legend: 11
    axis_labels: 14
    tick_labels: 11
  padding:
    wspace: 0.9
    left: 0.05
    right: 0.98
    top: 0.77
    bottom: 0.15
events:
  size: [15, 12]
  dpi: 150
  line_width: 3
  fontsize:
    title: 26
    legend: 16
    axis_labels: 22
    subplot_labels: 20
    tick_labels: 18
  location:
    legend_x: 0.117
    legend_y: 0.005
    title_x: 0.5
    title_y: 0.96
    label_xaxis_x: 0.5
    label_xaxis_y: 0.215
    label_yaxis_x: 0.05
    label_yaxis_y: 0.6
  padding:
    x_axis: 14
    w_space: 0.1
    subplot_title: 15
    top: 0.85
    bottom: 0.15
    subplot_threshold: 1.0
    subfig_h_space: 0.0
    threshold_ratio: 0.3
  events:
    height: 4
    width: 3.5
thresholds:
  size: [15, 12]
  dpi: null
  line_width: null
  fontsize:
    title: 18
    legend: null
    axis_labels: null
    subplot_labels: null
    tick_labels: 16
  location:
    legend_x: null
    legend_y: null
    title_x: null
    title_y: null
    label_xaxis_x: null
    label_xaxis_y: null
    label_yaxis_x: null
    label_yaxis_y: null
  padding:
    x_axis: null
    w_space: null
    subplot_title: 10
    top: null
    bottom: 0.42
    subplot_threshold: null
    subfig_h_space: null
    threshold_ratio: null
  events:
    height: null
    width: 0.6