experiment:
  parameter_matching: 'all'
  fig_save: True
  num_instances: 10
  order_randomization: True
  seed_offset: 0
parameters:
  plasticity.lambda_plus:
    enabled: True
    min: 0.13
    max: 0.17
    step: 0.01
    dtype: float
  plasticity.lambda_minus:
    enabled: True
    min: 0.003
    max: 0.005
    step: 0.0005
    dtype: float
  plasticity.lambda_h:
    enabled: True
    min: 0.010
    max: 0.03
    step: 0.005
    dtype: float
  synapses.p_exc_exc:
    enabled: False
    # values: [0.2, 0.4]
    min: 0.001
    max: 0.002
    step: 0.0005
    dtype: float
  plasticity.tau_plus:
    enabled: True
    min: 15
    max: 22
    step: 1
    dtype: int
  plasticity.target_rate_h:
    enabled: False
    min: 0.08
    max: 0.28
    step: 0.4
    dtype: float
  plasticity.homeostasis_depression_rate:
    enabled: False
    # values: [0.2, 0.4]
    min: 0.8
    max: 1.0
    step: 0.025
    dtype: float
