experiment:
  type: ''
  sequences: [['A', 'C', 'B'], ['D', 'C', 'B']]
  runtime: 0.44
  episodes: 100
  run_add_calib: False
plotting:
  size: [10, 12]
  file_type: 'pdf'
  save_figure: True
network:
  num_symbols: 4
  num_neurons: 15
encoding:
  dt_stm: 40e-3
  dt_seq: 100e-3
plasticity:
  type: 'original'
  learning_factor: 10
  permanence_max: 20.
  threshold: 10.
  y: 1.
  lambda_plus: 0.08e3
  lambda_minus: 0.0015e3
  lambda_h: 0.014e3
  target_rate_h: 1.
  tau_plus: 20e-3
  tau_h: 440e-3
  delta_t_min: 4e-3
  delta_t_max: 80e-3
  dt: 0.1e-3
neurons:
  inhibitory:
    v_rest: 60
    v_reset: 60
    v_thresh: 75
    tau_m: 2
    tau_syn_I: 10
    tau_syn_E: 0.5
    tau_refrac: 2
  excitatory:
    v_rest: 60
    v_reset: 60
    v_thresh: 120
    tau_m: 10
    tau_syn_I: [3, 1]
    tau_syn_E: [2, 5]
    tau_refrac: [60, 10]
synapses:
  w_ext_exc: 200
  w_exc_exc: 0.01
  w_exc_inh: 60
  w_inh_exc: -80
  p_exc_exc: 0.2
calibration:
  v_rest_calib: 275