experiment:
  id: 'test'
  sequences: [['A', 'C', 'B'], ['D', 'C', 'B']]
  runtime: null
  episodes: 100
  run_add_calib: False
  save_final: False
  save_auto: False
  save_auto_epoches: 5
  generate_rand_seed_offset: False
  seed_offset: null
  log_weights: True
  log_permanence: True
plotting:
  size: [10, 12]
  file_type: 'pdf'
  save_figure: True
performance:
  compute_performance: True
  method: "last_symbol"
network:
  num_symbols: 4
  num_neurons: 15
  pattern_size: 3
encoding:
  dt_stm: 40.e-3
  dt_seq: 100.e-3
  t_exc_start: 30.e-3
  t_scaling_factor: 1.e-3
plasticity:
  type: 'original'
  learning_factor: 1
  permanence_init_min: 0
  permanence_init_max: 8
  permanence_max: 20.
  threshold: 10.
  w_mature: 500
  y: 1
  lambda_plus: 0.08
  lambda_minus: 0.0015
  lambda_h: 0.014
  target_rate_h: 1.
  tau_plus: 20.e-3
  tau_h: null
  delta_t_min: 4.e-3
  delta_t_max: 75.e-3
  dt: 0.1e-3
neurons:
  inhibitory:
    v_rest: 60
    v_reset: 60
    v_thresh: 75
    tau_m: 2
    tau_syn_I: 10
    tau_syn_E: 0.5
    tau_refrac: 2
  excitatory:
    v_rest: [60, 60]
    v_reset: [100, 60]
    v_thresh: [120, 120]
    tau_m: 10
    tau_syn_I: [3, 1]
    tau_syn_E: [2, 5]
    tau_refrac: [60, 10]
synapses:
  dyn_inh_weights: False
  dyn_weight_calculation: False
  w_exc_inh_dyn: null
  w_ext_exc: 600
  w_exc_exc: 0.0
  w_exc_inh: 250
  w_inh_exc: -800
  p_exc_exc: 0.4
  receptor_ext_exc: "excitatory"
  receptor_exc_exc: "excitatory"
  receptor_exc_inh: "excitatory"
  receptor_inh_exc: "inhibitory"
  delay_ext_exc: 0.0
  delay_exc_exc: 0.0
  delay_exc_inh: 0.0
  delay_inh_exc: 0.0
  j_ext_exc_psp: None
  j_exc_inh_psp: None
  j_inh_exc_psp: None
calibration:
  v_rest_calib: 275
