performance:
  size: [15, 5]
  dpi: 150
  line_width: 3
  fontsize:
    title: 20
    sub_title: 18
    legend: 11
    axis_labels: 14
    tick_labels: 11
  padding:
    wspace: 0.9
    left: 0.05
    right: 0.98
    top: 0.77
    bottom: 0.15
events:
  size: [24, 10]
  dpi: 150
  line_width: 3
  fontsize:
    title: 26
    legend: 18
    axis_labels: 26
    subplot_labels: 20
    tick_labels: 18
  padding:
    x_axis: 14
    w_space: 0.04