experiment:
  parameter_matching: 'all'
  fig_save: True
  num_instances: 1
  order_randomization: True
parameters:
  Plasticity.lambda_plus:
    enabled: True
    min: 12
    max: 20
    step: 4
    dtype: int
  Plasticity.lambda_minus:
    enabled: False
    min: 0.002
    max: 0.08
    step: 0.002
    dtype: float
  Plasticity.lambda_h:
    enabled: True
    min: 4
    max: 16
    step: 2
    dtype: int
  Plasticity.target_rate_h:
    enabled: True
    min: 60
    max: 90
    step: 10
    dtype: int
  Plasticity.permanence_threshold:
    enabled: True
    min: 60
    max: 100
    step: 20
    dtype: int
  Plasticity.correlation_threshold:
    enabled: False
    min: 40
    max: 90
    step: 10
    dtype: int
  Synapses.w_ext_exc:
    enabled: False
    min: 46
    max: 58
    step: 2
    dtype: float
  Synapses.w_exc_inh:
    enabled: True
    min: 30
    max: 50
    step: 5
    dtype: int
  Synapses.w_inh_exc:
    enabled: False
    min: -360
    max: -280
    step: 10
    dtype: float
  Synapses.p_exc_exc:
    enabled: False
    min: 0.2
    max: 0.4
    step: 0.1
    dtype: float
  Plasticity.correlation_threshold:
    enabled: False
    min: 40
    max: 80
    step: 10
    dtype: float
